---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cabbooking-deployment
  labels:
    app: cabbooking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cabbooking
  template:
    metadata:
      labels:
        app: cabbooking
    spec:
      containers:
      - name: taxi-booking-container
        image: harishgorla5/project6:latest
        ports:
        - containerPort: 8080
        
---
apiVersion: v1
kind: Service
metadata:
  name: cabbooking-svc
  labels:
    app: cabbooking
spec:
  selector:
    app: cabbooking
  ports:
  - protocol: TCP
    port: 9004
    targetPort: 8080  # Ensure this matches the containerPort
  type: LoadBalancer
